/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cliente.Cliente;
import cliente.Notificable;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Es la interfaz donde el cliente podra jugar
 *
 * @author Karen Dayanna Castaño Orjuela
 * @author Carlos Alberto Campos Armero
 */
public class Home extends javax.swing.JFrame implements Notificable {

    private Cliente cliente;
    private String action;

    /**
     * Creates new form Juego
     */
    public Home(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = cliente;
        jLabelName.setText(cliente.getNombre());
        this.action = "";
        this.cliente.setNotificableRed(this);
        this.cliente.ejecutarCliente();
        
        piedra2.setEnabled(false);
        papel2.setEnabled(false);
        tijeras2.setEnabled(false);
        
        try {
            cliente.updateName(cliente.getNombre());
        } catch (IOException ex) {
            System.out.println("ERROR CREANDO CLIENTE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelName2 = new javax.swing.JLabel();
        piedra2 = new javax.swing.JButton();
        papel2 = new javax.swing.JButton();
        tijeras1 = new javax.swing.JButton();
        piedra1 = new javax.swing.JButton();
        papel1 = new javax.swing.JButton();
        tijeras2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        textGanador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabelName.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Usuario:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/linea.png"))); // NOI18N

        jLabelName2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelName2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName2.setText("Usuario:");

        piedra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piedra.png"))); // NOI18N
        piedra2.setBorderPainted(false);
        piedra2.setContentAreaFilled(false);

        papel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papel.png"))); // NOI18N
        papel2.setBorderPainted(false);
        papel2.setContentAreaFilled(false);

        tijeras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tijeras.png"))); // NOI18N
        tijeras1.setBorderPainted(false);
        tijeras1.setContentAreaFilled(false);
        tijeras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeras1ActionPerformed(evt);
            }
        });

        piedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piedra.png"))); // NOI18N
        piedra1.setBorderPainted(false);
        piedra1.setContentAreaFilled(false);
        piedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedra1ActionPerformed(evt);
            }
        });

        papel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papel.png"))); // NOI18N
        papel1.setBorderPainted(false);
        papel1.setContentAreaFilled(false);
        papel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papel1ActionPerformed(evt);
            }
        });

        tijeras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tijeras.png"))); // NOI18N
        tijeras2.setBorderPainted(false);
        tijeras2.setContentAreaFilled(false);
        tijeras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeras2ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        reiniciar.setAutoscrolls(true);
        reiniciar.setContentAreaFilled(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/linea.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(piedra2)
                .addGap(58, 58, 58)
                .addComponent(papel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tijeras2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(602, 602, 602))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(piedra1)
                                .addGap(28, 28, 28)
                                .addComponent(papel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(tijeras1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1134, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(papel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(piedra2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tijeras2)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(papel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(piedra1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(tijeras1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textGanador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(reiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(588, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tijeras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeras2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tijeras2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void piedra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedra1ActionPerformed
        if (this.action != "") {
            return;
        }
        this.action = "PIEDRA";
        papel1.setEnabled(false);
        tijeras1.setEnabled(false);
        try {
            cliente.setAction(this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR AL ENVIAR DATOS");
        }
    }//GEN-LAST:event_piedra1ActionPerformed

    private void papel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papel1ActionPerformed
        if (this.action != "") {
            return;
        }
        this.action = "PAPEL";
        piedra1.setEnabled(false);
        tijeras1.setEnabled(false);
        try {
            cliente.setAction(this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR AL ENVIAR DATOS");
        }
    }//GEN-LAST:event_papel1ActionPerformed

    private void tijeras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeras1ActionPerformed
        if (this.action != "") {
            return;
        }
        this.action = "TIJERAS";
        piedra1.setEnabled(false);
        papel1.setEnabled(false);
        try {
            cliente.setAction(this.action);
        } catch (IOException ex) {
            System.out.println(">>ERROR AL ENVIAR DATOS");
        }
    }//GEN-LAST:event_tijeras1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton papel1;
    private javax.swing.JButton papel2;
    private javax.swing.JButton piedra1;
    private javax.swing.JButton piedra2;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel textGanador;
    private javax.swing.JButton tijeras1;
    private javax.swing.JButton tijeras2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void login(String mensaje) {

    }

    @Override
    public void deshabilitarJuego(String mensaje) {
        piedra1.setEnabled(false);
        papel1.setEnabled(false);
        tijeras1.setEnabled(false);

        jLabelName2.setText(mensaje);
    }

    @Override
    public void habilitarJuego(String mensaje) {        
        piedra1.setEnabled(true);
        papel1.setEnabled(true);
        tijeras1.setEnabled(true);

        jLabelName2.setText(mensaje);
    }

    @Override
    public void jugar(JSONObject receivedJson) {
        if(receivedJson.has(jLabelName2.getText())){
            try {
                String actionOponente = receivedJson.getString(jLabelName2.getText());
                switch(actionOponente){
                    case "PIEDRA":
                        piedra2.setEnabled(true);
                        break;
                    case "PAPEL":
                        papel2.setEnabled(true);
                        break;
                    case "TIJERAS":
                        tijeras2.setEnabled(true);
                        break;
                }
                textGanador.setText(receivedJson.getString("ganador"));
            } catch (JSONException ex) {
                System.out.println("ERROR EN VISTA");
            }
        }
    }
}
